package app.views;

import core.Auth;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Dannyel
 */
public class Index extends javax.swing.JFrame {
    private int xPos, yPos;
    public Index() {
        initComponents();
        showPanel(new Start());
        this.lblLoginUser.setText(Auth.user.name + " " + Auth.user.lastname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        lblTaskManager = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        lblNavInfo = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        navPanel = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        btnStart = new javax.swing.JPanel();
        lblStart = new javax.swing.JLabel();
        btnBikes = new javax.swing.JPanel();
        lblBikes = new javax.swing.JLabel();
        btnSales = new javax.swing.JPanel();
        lblSales = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        btnUsers = new javax.swing.JPanel();
        lblUsers = new javax.swing.JLabel();
        btnEmployes = new javax.swing.JPanel();
        lblEmployes = new javax.swing.JLabel();
        btnBrands = new javax.swing.JPanel();
        lblBrands = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        lblESPE = new javax.swing.JLabel();
        lblLoginUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanel.setBackground(new java.awt.Color(48, 161, 163));

        lblTaskManager.setFont(new java.awt.Font("Roboto", 3, 30)); // NOI18N
        lblTaskManager.setForeground(new java.awt.Color(255, 255, 255));
        lblTaskManager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaskManager.setText("SDB");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTaskManager, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTaskManager, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        bgPanel.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        topPanel.setBackground(new java.awt.Color(0, 134, 190));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        lblNavInfo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblNavInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblNavInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNavInfo.setText("Inicio");

        lblExit.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("--");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(lblNavInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 627, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNavInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        bgPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 70));

        navPanel.setBackground(new java.awt.Color(96, 188, 137));

        lblAdmin.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmin.setText("Administración");

        btnStart.setBackground(new java.awt.Color(123, 205, 120));
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartMouseExited(evt);
            }
        });

        lblStart.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblStart.setForeground(new java.awt.Color(255, 255, 255));
        lblStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStart.setText("Inicio");

        javax.swing.GroupLayout btnStartLayout = new javax.swing.GroupLayout(btnStart);
        btnStart.setLayout(btnStartLayout);
        btnStartLayout.setHorizontalGroup(
            btnStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnStartLayout.setVerticalGroup(
            btnStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        btnBikes.setBackground(new java.awt.Color(123, 205, 120));
        btnBikes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBikes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBikesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBikesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBikesMouseExited(evt);
            }
        });

        lblBikes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblBikes.setForeground(new java.awt.Color(255, 255, 255));
        lblBikes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBikes.setText("Bicicletas");

        javax.swing.GroupLayout btnBikesLayout = new javax.swing.GroupLayout(btnBikes);
        btnBikes.setLayout(btnBikesLayout);
        btnBikesLayout.setHorizontalGroup(
            btnBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBikes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        btnBikesLayout.setVerticalGroup(
            btnBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBikes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        btnSales.setBackground(new java.awt.Color(123, 205, 120));
        btnSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalesMouseExited(evt);
            }
        });

        lblSales.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblSales.setForeground(new java.awt.Color(255, 255, 255));
        lblSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSales.setText("Ventas");

        javax.swing.GroupLayout btnSalesLayout = new javax.swing.GroupLayout(btnSales);
        btnSales.setLayout(btnSalesLayout);
        btnSalesLayout.setHorizontalGroup(
            btnSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnSalesLayout.setVerticalGroup(
            btnSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        btnLogout.setBackground(new java.awt.Color(0, 134, 190));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblLogout.setBackground(new java.awt.Color(255, 255, 255));
        lblLogout.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("Cerrar Sesión");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnLogoutLayout = new javax.swing.GroupLayout(btnLogout);
        btnLogout.setLayout(btnLogoutLayout);
        btnLogoutLayout.setHorizontalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnLogoutLayout.setVerticalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        btnUsers.setBackground(new java.awt.Color(123, 205, 120));
        btnUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsersMouseExited(evt);
            }
        });

        lblUsers.setBackground(new java.awt.Color(255, 255, 255));
        lblUsers.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblUsers.setForeground(new java.awt.Color(255, 255, 255));
        lblUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsers.setText("Usuarios");

        javax.swing.GroupLayout btnUsersLayout = new javax.swing.GroupLayout(btnUsers);
        btnUsers.setLayout(btnUsersLayout);
        btnUsersLayout.setHorizontalGroup(
            btnUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnUsersLayout.setVerticalGroup(
            btnUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        btnEmployes.setBackground(new java.awt.Color(123, 205, 120));
        btnEmployes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmployesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmployesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmployesMouseExited(evt);
            }
        });

        lblEmployes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblEmployes.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployes.setText("Empleados");

        javax.swing.GroupLayout btnEmployesLayout = new javax.swing.GroupLayout(btnEmployes);
        btnEmployes.setLayout(btnEmployesLayout);
        btnEmployesLayout.setHorizontalGroup(
            btnEmployesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEmployes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEmployesLayout.setVerticalGroup(
            btnEmployesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEmployes, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        btnBrands.setBackground(new java.awt.Color(123, 205, 120));
        btnBrands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrands.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrandsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBrandsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBrandsMouseExited(evt);
            }
        });

        lblBrands.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblBrands.setForeground(new java.awt.Color(255, 255, 255));
        lblBrands.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrands.setText("Marcas");

        javax.swing.GroupLayout btnBrandsLayout = new javax.swing.GroupLayout(btnBrands);
        btnBrands.setLayout(btnBrandsLayout);
        btnBrandsLayout.setHorizontalGroup(
            btnBrandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBrands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnBrandsLayout.setVerticalGroup(
            btnBrandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBrands, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBikes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmployes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBrands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBikes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmployes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bgPanel.add(navPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 250, 720));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setAutoscrolls(true);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        bgPanel.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 1030, 590));

        lblESPE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/core-img/ESPE-100.png"))); // NOI18N
        bgPanel.add(lblESPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        lblLoginUser.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        lblLoginUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLoginUser.setText("User");
        bgPanel.add(lblLoginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 350, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - this.xPos, y - this.yPos);
    }//GEN-LAST:event_topPanelMouseDragged

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        this.xPos = evt.getX();
        this.yPos = evt.getY();
    }//GEN-LAST:event_topPanelMousePressed

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        showPanel(new Start());
        this.lblNavInfo.setText("Inicio");
    }//GEN-LAST:event_btnStartMouseClicked

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        hoverEntered(this.btnStart);
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        hoverExited(this.btnStart);
    }//GEN-LAST:event_btnStartMouseExited

    private void btnBikesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBikesMouseClicked
        showPanel(new stocks());
        this.lblNavInfo.setText("stocks");
    }//GEN-LAST:event_btnBikesMouseClicked

    private void btnBikesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBikesMouseEntered
        hoverEntered(this.btnBikes);
    }//GEN-LAST:event_btnBikesMouseEntered

    private void btnBikesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBikesMouseExited
        hoverExited(this.btnBikes);
    }//GEN-LAST:event_btnBikesMouseExited

    private void btnSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseClicked
        showPanel(new ventas());
        this.lblNavInfo.setText("ventas");
    }//GEN-LAST:event_btnSalesMouseClicked

    private void btnSalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseEntered
        hoverEntered(this.btnSales);
    }//GEN-LAST:event_btnSalesMouseEntered

    private void btnSalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseExited
        hoverExited(this.btnSales);
    }//GEN-LAST:event_btnSalesMouseExited

    private void btnUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseClicked
        //showPanel(new Users());
        this.lblNavInfo.setText("Administrar Usuarios");
    }//GEN-LAST:event_btnUsersMouseClicked

    private void btnUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseEntered
        hoverEntered(this.btnUsers);
    }//GEN-LAST:event_btnUsersMouseEntered

    private void btnUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseExited
        hoverExited(this.btnUsers);
    }//GEN-LAST:event_btnUsersMouseExited

    private void btnEmployesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployesMouseClicked
       // METODO PARA LLAMAR A JFROM EMPLEADO
        showPanel(new Empleado());
        this.lblNavInfo.setText("Administrar empleados");
    }//GEN-LAST:event_btnEmployesMouseClicked

    private void btnEmployesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployesMouseEntered
        hoverEntered(this.btnEmployes);
    }//GEN-LAST:event_btnEmployesMouseEntered

    private void btnEmployesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployesMouseExited
        hoverExited(this.btnEmployes);
    }//GEN-LAST:event_btnEmployesMouseExited

    private void btnBrandsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrandsMouseClicked
        // METODO PARA LLAMAR A JFROM EMPLEADO
        showPanel(new Brands());
        this.lblNavInfo.setText("Administrar marcas");
    }//GEN-LAST:event_btnBrandsMouseClicked

    private void btnBrandsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrandsMouseEntered
        hoverEntered(this.btnBrands);
    }//GEN-LAST:event_btnBrandsMouseEntered

    private void btnBrandsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrandsMouseExited
        hoverExited(this.btnBrands);
    }//GEN-LAST:event_btnBrandsMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        Auth.unauthenticate();
        this.setVisible(false);
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void hoverEntered(JPanel btnPanel)
    {
        btnPanel.setBackground(new Color(0, 0, 0));
    }
    
    private void hoverExited(JPanel btnPanel)
    {
        btnPanel.setBackground(new Color(123, 205, 120));
    }
    
    public void showPanel(JPanel p)
    {
        p.setSize(1030, 590);
        p.setLocation(0, 0);
        
        this.contentPanel.removeAll();
        this.contentPanel.add(p, BorderLayout.CENTER);
        this.contentPanel.revalidate();
        this.contentPanel.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JPanel btnBikes;
    private javax.swing.JPanel btnBrands;
    private javax.swing.JPanel btnEmployes;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JPanel btnSales;
    private javax.swing.JPanel btnStart;
    private javax.swing.JPanel btnUsers;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblBikes;
    private javax.swing.JLabel lblBrands;
    private javax.swing.JLabel lblESPE;
    private javax.swing.JLabel lblEmployes;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLoginUser;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblNavInfo;
    private javax.swing.JLabel lblSales;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTaskManager;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JPanel navPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
