package app.views;

import core.Auth;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dannyel
 */
public class Login extends javax.swing.JFrame {
    private int xPos, yPos;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        sideLogo = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        jsPass = new javax.swing.JSeparator();
        jsUser = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JPanel();
        lblLoginButton = new javax.swing.JLabel();
        topLogo = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(96, 188, 137));

        sideLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/core-img/Logo-ESPE.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 170, 400));

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 670, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 30));

        lblLogin.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblLogin.setText("Iniciar Sesión");
        bg.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lblUser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblUser.setText("Usuario");
        bg.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        txtUser.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUser.setForeground(new java.awt.Color(204, 204, 204));
        txtUser.setText("Ingrese su Nombre de Usuario");
        txtUser.setBorder(null);
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUserMousePressed(evt);
            }
        });
        bg.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 350, 30));

        lblPass.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblPass.setText("Contraseña");
        bg.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        bg.add(jsPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 350, -1));
        bg.add(jsUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 350, -1));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPass.setForeground(new java.awt.Color(204, 204, 204));
        txtPass.setText("********");
        txtPass.setBorder(null);
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassMousePressed(evt);
            }
        });
        bg.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 350, 30));

        btnLogin.setBackground(new java.awt.Color(96, 188, 137));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        lblLoginButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginButton.setText("Ingresar");
        lblLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 120, 40));

        topLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/core-img/ESPE-100.png"))); // NOI18N
        bg.add(topLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        bg.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 210, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        this.lblExit.setForeground(Color.red);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        this.lblExit.setForeground(Color.black);
    }//GEN-LAST:event_lblExitMouseExited

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - this.xPos, y - this.yPos);
    }//GEN-LAST:event_topPanelMouseDragged

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        this.xPos = evt.getX();
        this.yPos = evt.getY();
    }//GEN-LAST:event_topPanelMousePressed

    private void txtUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMousePressed
        if (txtUser.getText().equals("Ingrese su Nombre de Usuario"))
        {
            this.txtUser.setText("");
            this.txtUser.setForeground(Color.BLACK);
        }

        if (String.valueOf(txtPass.getPassword()).isEmpty())
        {
            this.txtPass.setText("********");
            this.txtPass.setForeground(Color.GRAY);
        }

    }//GEN-LAST:event_txtUserMousePressed

    private void txtPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMousePressed
        if (String.valueOf(txtPass.getPassword()).equals("********"))
        {
            this.txtPass.setText("");
            this.txtPass.setForeground(Color.BLACK);
        }

        if (txtUser.getText().isEmpty())
        {
            this.txtUser.setText("Ingrese su Nombre de Usuario");
            this.txtUser.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtPassMousePressed

    private void lblLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginButtonMouseClicked
        if (!(txtUser.getText().isEmpty()) && !(String.valueOf(txtPass.getPassword()).isEmpty()))
        if (!(String.valueOf(txtPass.getPassword()).equals("********")) && !(txtUser.getText().equals("Ingrese su Nombre de Usuario")))
        {
            try {
                boolean auth = Auth.authenticate(txtUser.getText(), String.valueOf(txtPass.getPassword()));
                
                if (auth) {
                    System.out.println("Login Success");
                    Index indexWindow = new Index();
                    indexWindow.setVisible(true);

                    this.setVisible(false);
                } else {
                    System.out.println("Login Error");
                    this.lblError.setText("Error. Verifique sus credenciales");
                }
                
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblLoginButtonMouseClicked

    private void lblLoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginButtonMouseEntered
        this.btnLogin.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_lblLoginButtonMouseEntered

    private void lblLoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginButtonMouseExited
        this.btnLogin.setBackground(new Color(96, 188, 137));
    }//GEN-LAST:event_lblLoginButtonMouseExited

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        //
    }//GEN-LAST:event_btnLoginMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jsPass;
    private javax.swing.JSeparator jsUser;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLoginButton;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel sideLogo;
    private javax.swing.JLabel topLogo;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
